API.Function("AudioOff","Scarlett 1")
API.Function("AudioOff","Scarlett 2")
API.Function("AudioOff","Scarlett 3")
API.Function("AudioOff","Scarlett 4")
'API.Function("AudioOff","Scarlett 5")
'API.Function("AudioOff","Scarlett 6")
'API.Function("AudioOff","Scarlett 7")
'API.Function("AudioOff","Scarlett 8")
API.Function("BusXAudioOff",Value:="C")
API.Function("AudioOff","Behringer 1")
API.Function("AudioOff","Behringer 2")
API.Function("AudioOff","Behringer 3")
API.Function("AudioOff","Behringer 4")
API.Function("AudioOff","Right")
API.Function("AudioOff","Prelude")
API.Function("AudioOff","Opening Hymn")
API.Function("AudioOff","Hebrew Reading")
API.Function("AudioOff","Psalm")
API.Function("AudioOff","Epistle")
API.Function("AudioOff","Sermon")
API.Function("AudioOff","Offertory Anthem")
API.Function("AudioOff","Communion Hymn")
API.Function("AudioOff","Second Communion Hymn")
API.Function("AudioOff","Closing Hymn")
API.Function("AudioOff","Intro Music List")
