API.Function("ScriptStart",Value:="allAudioOff")

API.Function("Pause","Intro Music List")
API.Function("Pause","Prelude")
API.Function("Pause","Opening Hymn")
API.Function("Pause","Hebrew Reading")
API.Function("Pause","Psalm")
API.Function("Pause","Epistle")
API.Function("Pause","Sermon")
API.Function("Pause","Prayers of the People")
API.Function("Pause","Offertory Anthem")
API.Function("Pause","Communion Hymn")
API.Function("Pause","Second Communion Hymn")
API.Function("Pause","Closing Hymn")

API.Function("OverlayInput1Off")
API.Function("OverlayInput2Off")
API.Function("OverlayInput3Off")
API.Function("OverlayInput4Off")
API.Function("Cut","Blank")
API.Function("PreviewInput","Blank")
API.Function("AudioBusOff","Prelude","B")
API.Function("AudioBusOff","Opening Hymn","B")
API.Function("AudioBusOff","Hebrew Reading","B")
API.Function("AudioBusOff","Prayers of the People","B")
API.Function("AudioBusOff","Offertory Anthem","B")
API.Function("AudioBusOff","Communion Hymn","B")
API.Function("AudioBusOff","Closing Hymn","B")
API.Function("BusXAudioOff",Value:="C")