'API.Function("Restart","Intro Music List")
API.Function("Restart","Announcements")
'API.Function("AudioAutoOff","Intro Music List")
'API.Function("AudioOn","Intro Music List")
API.Function("OverlayInput1Out")
API.Function("OverlayInput1In","Annoucements Overlay")
'API.Function("OverlayInput2In","Intro Music List")
API.Function("Merge","Announcements",1000)
'API.Function("Play","Intro Music List")
API.Function("Play","Announcements")
'API.Function("ScriptStart",Value:="choirOn")