API.Function("AudioBusOff","Prelude","B")
API.Function("AudioBusOff","Opening Hymn","B")
API.Function("AudioBusOff","Hebrew Reading","B")
API.Function("AudioBusOff","Prayers of the People","B")
API.Function("AudioBusOff","Offertory Anthem","B")
API.Function("AudioBusOff","Communion Hymn","B")
API.Function("AudioBusOff","Closing Hymn","B")