dim choir1 as string = Input.Find("variables.gtzip").Text("micChoir1.Text")
dim choir2 as string = Input.Find("variables.gtzip").Text("micChoir2.Text")
dim choir3 as string = Input.Find("variables.gtzip").Text("micChoir3.Text")
dim solo as string = Input.Find("variables.gtzip").Text("micSolo.Text")

dim josh as string = Input.Find("variables.gtzip").Text("micJosh.Text")
dim judy as string = Input.Find("variables.gtzip").Text("micJudy.Text")
dim mic3 as string = Input.Find("variables.gtzip").Text("mic3.Text")
dim ambo as string = Input.Find("variables.gtzip").Text("micAmbo.Text")
dim em as string = Input.Find("variables.gtzip").Text("micEM.Text")
dim altar as string = Input.Find("variables.gtzip").Text("micAltar.Text")
dim crowd as string = Input.Find("variables.gtzip").Text("micCrowd.Text")

API.Function("AudioOff",josh)
API.Function("AudioOff",judy)
API.Function("AudioOff",mic3)
API.Function("AudioOff",ambo)
API.Function("AudioOff",em)
API.Function("AudioOff",altar)
API.Function("AudioOff",crowd)

API.Function("AudioOn",choir1)
API.Function("AudioOn",choir2)
API.Function("AudioOn",choir3)
API.Function("AudioOn",solo)
API.Function("BusXAudioOn",Value:="C")