dim josh as string = Input.Find("variables.gtzip").Text("micJosh.Text")
dim judy as string = Input.Find("variables.gtzip").Text("micJudy.Text")
dim mic3 as string = Input.Find("variables.gtzip").Text("mic3.Text")
dim ambo as string = Input.Find("variables.gtzip").Text("micAmbo.Text")
dim em as string = Input.Find("variables.gtzip").Text("micEM.Text")
dim altar as string = Input.Find("variables.gtzip").Text("micAltar.Text")
dim crowd as string = Input.Find("variables.gtzip").Text("micCrowd.Text")

API.Function("AudioOff",josh)
API.Function("AudioOff",mic3)
API.Function("AudioOff",ambo)
API.Function("AudioOff",em)
API.Function("AudioOff",crowd)
API.Function("AudioOff",altar)
API.Function("BusXAudioOff",Value:="C")

API.Function("OverlayInput1Out")
'API.Function("Merge","Right")
API.Function("Merge","Center")
API.Function("AudioOn","Scarlett 3")