API.Function("AudioOff","Scarlett 1")
API.Function("AudioOff","Scarlett 2")
API.Function("AudioOff","Scarlett 3")
API.Function("AudioOff","Scarlett 4")
'API.Function("AudioOff","Scarlett 5")
'API.Function("AudioOff","Scarlett 6")
'API.Function("AudioOff","Scarlett 7")
'API.Function("AudioOff","Scarlett 8")
API.Function("BusXAudioOff",Value:="C")
API.Function("AudioOff","Behringer 1")
API.Function("AudioOff","Behringer 2")
API.Function("AudioOff","Behringer 3")
API.Function("AudioOff","Behringer 4")
API.Function("AudioOff","Right")
API.Function("SetDynamicInput1",Value:=" ")