dim camera as string = Input.Find("variables.gtzip").Text("CameraOffertory.Text")
dim camera2 as string = Input.Find("variables.gtzip").Text("Cam2Offertory.Text")
'API.Function("SetMultiViewOverlay",Input:="MultiView 1",Value:="2,Right")
'API.Function("SetMultiViewOverlay",Input:="MultiView 1",Value:="1,Center")
API.Function("AudioBusOn",Input:="Offertory Anthem",Value:="B")
API.Function("AudioBusOff",Input:="Prayers of the People",Value:="B")
API.Function("BusXAudioOn",Value:="C")
sleep(3000)
API.Function("PreviewInput",Input:=camera2)