API.Function("OverlayInput1Out")
Sleep(1200)
API.Function("DataSourceSelectRow",Value:="Responses,pop,0")
API.Function("DataSourceSelectRow",Value:="Responses,psalm,0")
API.Function("DataSourceSelectRow",Value:="Responses,prayers,0")
API.Function("DataSourceSelectRow",Value:="Responses,opening hymn,0")
API.Function("DataSourceSelectRow",Value:="Responses,offertory,0")
API.Function("DataSourceSelectRow",Value:="Responses,communion hymn,0")
API.Function("DataSourceSelectRow",Value:="Responses,closing hymn,0")
API.Function("DataSourceSelectRow",Value:="Responses,affirmation,0")