API.Function("ScriptStart",Value:="BusBOff")
API.Function("ScriptStart",Value:="allAudioOff")
API.Function("OverlayInputAllOff")

API.Function("Restart","Prelude")
API.Function("Restart","Opening Hymn")
API.Function("Restart","Hebrew Reading")
API.Function("Restart","Psalm")
API.Function("Restart","Epistle")
API.Function("Restart","Sermon")
API.Function("Restart","Offertory Anthem")
API.Function("Restart","Communion Hymn")
API.Function("Restart","Second Communion Hymn")
API.Function("Restart","Closing Hymn")
API.Function("Restart","Announcements")

API.Function("DataSourceSelectRow",Value:="Responses,pop,0")
API.Function("DataSourceSelectRow",Value:="Responses,psalm,0")
API.Function("DataSourceSelectRow",Value:="Responses,prayers,0")
API.Function("DataSourceSelectRow",Value:="Responses,opening hymn,0")
API.Function("DataSourceSelectRow",Value:="Responses,offertory,0")
API.Function("DataSourceSelectRow",Value:="Responses,communion hymn,0")
API.Function("DataSourceSelectRow",Value:="Responses,closing hymn,0")
API.Function("DataSourceSelectRow",Value:="Responses,affirmation,0")

' Make sure individual choir mics are on, but the choir bus (C) is off
dim choir1 as string = Input.Find("variables.gtzip").Text("micChoir1.Text")
dim choir2 as string = Input.Find("variables.gtzip").Text("micChoir2.Text")
dim choir3 as string = Input.Find("variables.gtzip").Text("micChoir3.Text")
dim solo as string = Input.Find("variables.gtzip").Text("micSolo.Text")
API.Function("BusXAudioOff",Value:="C")
API.Function("AudioOn",choir1)
API.Function("AudioOn",choir2)
API.Function("AudioOn",choir3)
API.Function("AudioOn",solo)

API.Function("PreviewInput","Blank")
API.Function("Merge","Opening Logo")
API.Function("FullscreenOn")